import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import styles from './PrivacyPolicy.module.css'; // Reuse PrivacyPolicy styles for consistency

export default function TermsOfService() {
    const navigate = useNavigate();
    const { t, i18n } = useTranslation();
    const isKo = i18n.language === 'ko';

    return (
        <motion.section
            className={styles.container}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
        >
            <header className={styles.header}>
                <button className={styles.backBtn} onClick={() => navigate(-1)}>
                    {t('common.back')}
                </button>
                <h1 className={styles.title}>{t('common.terms')}</h1>
            </header>

            <div className={styles.content}>
                <p className={styles.lastUpdated}>
                    {isKo ? '최종 수정일: 2026년 2월 18일' : 'Last Updated: February 18, 2026'}
                </p>

                {isKo ? (
                    <>
                        <section className={styles.section}>
                            <h2>1. 목적</h2>
                            <p>본 약관은 애니매치(AniMatch)(이하 '서비스')가 제공하는 모든 서비스의 이용 조건 및 절차, 이용자와 서비스의 권리, 의무 및 책임 사항을 규정함을 목적으로 합니다.</p>
                        </section>

                        <section className={styles.section}>
                            <h2>2. 서비스의 이용</h2>
                            <ul>
                                <li>이용자는 본인의 사진을 업로드하여 AI 기반 애니메이션 캐릭터 매칭 서비스를 이용할 수 있습니다.</li>
                                <li>서비스에서 제공하는 매칭 결과는 AI 알고리즘에 의한 확률적 결과이며, 절대적인 정의나 기준이 될 수 없습니다.</li>
                            </ul>
                        </section>

                        <section className={styles.section}>
                            <h2>3. 면책조항 (Disclaimer)</h2>
                            <p>서비스는 다음 사항에 대해 책임을 지지 않습니다.</p>
                            <ul>
                                <li><strong>결과의 정확성:</strong> AI 매칭 결과는 오락용이며 실제 인물과의 유사성이나 성격 일치를 보장하지 않습니다. 결과를 진지한 판단의 근거로 사용하는 것에 대해 서비스는 책임지지 않습니다.</li>
                                <li><strong>심리적 영향:</strong> 매칭 결과로 인해 이용자가 느끼는 주관적인 감정이나 심리적 변화에 대해 서비스는 책임지지 않습니다.</li>
                                <li><strong>데이터 손실 및 기술적 오류:</strong> 통신망 장애, 서버 점검 등으로 인한 서비스 중단이나 데이터 일시적 오류에 대해 책임지지 않습니다.</li>
                                <li><strong>제3자 링크:</strong> 서비스 내에 포함된 광고나 제3자의 사이트 링크를 통해 발생한 결과에 대해 책임지지 않습니다.</li>
                            </ul>
                        </section>

                        <section className={styles.section}>
                            <h2>4. 이용자의 의무</h2>
                            <ul>
                                <li>타인의 사진을 도용하거나 부적절한 이미지를 업로드하여 서비스를 오용해서는 안 됩니다.</li>
                                <li>공공질서 및 미풍양속에 반하는 행위를 하여 서비스 운영을 방해해서는 안 됩니다.</li>
                            </ul>
                        </section>

                        <section className={styles.section}>
                            <h2>5. 약관의 변경</h2>
                            <p>서비스는 필요한 경우 관련 법령을 위배하지 않는 범위 내에서 본 약관을 개정할 수 있습니다. 개정된 약관은 서비스 내 공지사항을 통해 고지됩니다.</p>
                        </section>
                    </>
                ) : (
                    <>
                        <section className={styles.section}>
                            <h2>1. Purpose</h2>
                            <p>These Terms of Service outline the conditions and procedures for using AniMatch (the 'Service'), as well as the rights, obligations, and responsibilities of both the user and the Service.</p>
                        </section>

                        <section className={styles.section}>
                            <h2>2. Use of Service</h2>
                            <ul>
                                <li>Users can access AI-based anime character matching services by uploading their photos.</li>
                                <li>Matching results provided by the service are probabilistic outcomes generated by AI algorithms and should not be considered absolute definitions or standards.</li>
                            </ul>
                        </section>

                        <section className={styles.section}>
                            <h2>3. Disclaimer</h2>
                            <p>The Service is not responsible for the following:</p>
                            <ul>
                                <li><strong>Accuracy of Results:</strong> AI matching results are for entertainment purposes only and do not guarantee similarity or personality match. The Service is not liable for outcomes resulting from treating matches as a basis for serious judgment.</li>
                                <li><strong>Psychological Impact:</strong> The Service is not responsible for subjective emotions or psychological changes experienced by users as a result of matching results.</li>
                                <li><strong>Data Loss and Technical Errors:</strong> The Service is not liable for technical issues such as network failures or server maintenance that may cause service interruptions or temporary data errors.</li>
                                <li><strong>Third-party Links:</strong> The Service is not responsible for outcomes related to advertisements or links to third-party sites included within the service.</li>
                            </ul>
                        </section>

                        <section className={styles.section}>
                            <h2>4. User Obligations</h2>
                            <ul>
                                <li>Users must not misuse the service by stealing others' photos or uploading inappropriate images.</li>
                                <li>Users must not interfere with the service's operation by engaging in acts that violate public order or morals.</li>
                            </ul>
                        </section>

                        <section className={styles.section}>
                            <h2>5. Amendments</h2>
                            <p>The Service may amend these terms as necessary within the scope of relevant laws. Amended terms will be announced through notices within the Service.</p>
                        </section>
                    </>
                )}
            </div>

            <footer className={styles.footer}>
                <button className={styles.homeBtn} onClick={() => navigate('/')}>
                    {t('common.backToHome')}
                </button>
            </footer>
        </motion.section>
    );
}
